# Generated by Django 5.1.4 on 2025-01-26 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('especialidad', models.CharField(choices=[('musculacion', 'Musculación'), ('spinning', 'Spinning'), ('yoga', 'Yoga'), ('bailoterapia', 'Bailoterapia'), ('natacion', 'Natación'), ('crossfit', 'Crossfit'), ('entrenamiento funcional', 'Entrenamiento funcional')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('edad', models.PositiveIntegerField()),
                ('telefono', models.CharField(max_length=20)),
                ('tipo_clase', models.CharField(choices=[('musculacion', 'Musculación'), ('spinning', 'Spinning'), ('yoga', 'Yoga'), ('bailoterapia', 'Bailoterapia'), ('natacion', 'Natación'), ('crossfit', 'Crossfit'), ('pase libre', 'Pase libre')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('duracion', models.DurationField(help_text='Duración de la actividad (ejemplo: 01:30:00)')),
                ('horario', models.TimeField(help_text='Hora de inicio de la actividad')),
                ('cupo_maximo', models.IntegerField(help_text='Cantidad máxima de participantes')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='AppCoder.instructor')),
            ],
        ),
    ]
