# Generated by Django 5.1.5 on 2025-01-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='cupo_disponible',
            field=models.IntegerField(default=40, help_text='Cantidad de cupos disponibles'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='cupo_maximo',
            field=models.IntegerField(default=40, help_text='Cantidad máxima de participantes'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='duracion',
            field=models.CharField(choices=[('00:30:00', '30 minutos'), ('01:00:00', '1 hora'), ('01:30:00', '1 hora y 30 minutos'), ('02:00:00', '2 horas')], default='01:00:00', max_length=8),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='horario',
            field=models.CharField(choices=[('06:00:00', '06:00 AM'), ('07:00:00', '07:00 AM'), ('08:00:00', '08:00 AM'), ('09:00:00', '09:00 AM'), ('10:00:00', '10:00 AM'), ('11:00:00', '11:00 AM'), ('12:00:00', '12:00 PM'), ('13:00:00', '01:00 PM'), ('14:00:00', '02:00 PM'), ('15:00:00', '03:00 PM'), ('16:00:00', '04:00 PM'), ('17:00:00', '05:00 PM'), ('18:00:00', '06:00 PM'), ('19:00:00', '07:00 PM'), ('20:00:00', '08:00 PM')], default='06:00:00', max_length=8),
        ),
    ]
