# Generated by Django 5.1.4 on 2025-01-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='curso',
            field=models.CharField(default='sin curso', max_length=100),
        ),
    ]
