# Generated by Django 5.1.4 on 2025-01-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_profesor_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('especialidad', models.CharField(choices=[('musculacion', 'Musculación'), ('spinning', 'Spinning'), ('yoga', 'Yoga'), ('bailoterapia', 'Bailoterapia'), ('natacion', 'Natación'), ('crossfit', 'Crossfit'), ('entrenamiento funcional', 'Entrenamiento funcional')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('edad', models.PositiveIntegerField()),
                ('telefono', models.CharField(max_length=20)),
                ('tipo_clase', models.CharField(choices=[('musculacion', 'Musculación'), ('spinning', 'Spinning'), ('yoga', 'Yoga'), ('bailoterapia', 'Bailoterapia'), ('natacion', 'Natación'), ('crossfit', 'Crossfit'), ('pase libre', 'Pase libre')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
