# Generated by Django 5.1.5 on 2025-01-29 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_remove_actividad_cupo_disponible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='AppCoder.instructor'),
        ),
    ]
