# Generated by Django 5.1.5 on 2025-01-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
