# Generated by Django 5.1.5 on 2025-01-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='biografia',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='birthday',
            new_name='fecha_nacimineto',
        ),
        migrations.AddField(
            model_name='profile',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
