# Generated by Django 5.1.5 on 2025-01-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccounts', '0002_rename_bio_profile_biografia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fecha_nacimineto',
            new_name='fecha_de_nacimineto',
        ),
        migrations.AddField(
            model_name='profile',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
