# Generated by Django 5.1.5 on 2025-01-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccounts', '0003_rename_fecha_nacimineto_profile_fecha_de_nacimineto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fecha_de_nacimineto',
            new_name='fecha_de_nacimiento',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default='avatars/user.png', max_length=255),
        ),
    ]
