# Generated by Django 5.1.5 on 2025-01-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccounts', '0006_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(choices=[('avatars/avataruser.png', 'Avatar por defecto'), ('avatars/avatar1.png', 'Avatar 1'), ('avatars/avatar2.png', 'Avatar 2'), ('avatars/avatar3.png', 'Avatar 3'), ('avatars/avatar4.png', 'Avatar 4'), ('avatars/avatar5.png', 'Avatar 5'), ('avatars/avatar6.png', 'Avatar 6'), ('avatars/avatar7.png', 'Avatar 7'), ('avatars/avatar8.png', 'Avatar 8'), ('avatars/avatar9.png', 'Avatar 9'), ('avatars/avatar10.png', 'Avatar 10'), ('avatars/avatar11.png', 'Avatar 11'), ('avatars/avatar12.png', 'Avatar 12'), ('avatars/avatar13.png', 'Avatar 13')], default='avatars/avataruser.png', max_length=255),
        ),
    ]
