# Generated by Django 5.1.5 on 2025-01-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccounts', '0007_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/avataruser.png', null=True, upload_to='avatars/'),
        ),
    ]
